---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.ctn-solutions.io
  resources:
  - clients
  - clientscopes
  - groups
  - identityproviders
  - realmroles
  - realms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.ctn-solutions.io
  resources:
  - clients/finalizers
  - clientscopes/finalizers
  - groups/finalizers
  - identityproviders/finalizers
  - realmroles/finalizers
  - realms/finalizers
  verbs:
  - update
- apiGroups:
  - keycloak.ctn-solutions.io
  resources:
  - clients/status
  - clientscopes/status
  - groups/status
  - identityproviders/status
  - keycloakconnections/status
  - realmroles/status
  - realms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keycloak.ctn-solutions.io
  resources:
  - keycloakconnections
  verbs:
  - get
  - list
  - watch
