---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keycloak.ctn-solutions.io
  resources:
  - client
  - clientscope
  - group
  - identityprovider
  - realmrole
  - realms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.ctn-solutions.io
  resources:
  - client/finalizers
  - clientscope/finalizers
  - group/finalizers
  - identityprovider/finalizers
  - realmrole/finalizers
  - realms/finalizers
  verbs:
  - update
- apiGroups:
  - keycloak.ctn-solutions.io
  resources:
  - client/status
  - clientscope/status
  - group/status
  - identityprovider/status
  - keycloakconnections/status
  - realmrole/status
  - realms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keycloak.ctn-solutions.io
  resources:
  - keycloakconnections
  verbs:
  - get
  - list
  - watch
