apiVersion: keycloak.ctn-solutions.io/v1alpha1
kind: Client
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: client-sample
spec:
  # TODO(user): Add fields here
