//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Client) DeepCopyInto(out *Client) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Client.
func (in *Client) DeepCopy() *Client {
	if in == nil {
		return nil
	}
	out := new(Client)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Client) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientList) DeepCopyInto(out *ClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Client, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientList.
func (in *ClientList) DeepCopy() *ClientList {
	if in == nil {
		return nil
	}
	out := new(ClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientScope) DeepCopyInto(out *ClientScope) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientScope.
func (in *ClientScope) DeepCopy() *ClientScope {
	if in == nil {
		return nil
	}
	out := new(ClientScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClientScope) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientScopeList) DeepCopyInto(out *ClientScopeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClientScope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientScopeList.
func (in *ClientScopeList) DeepCopy() *ClientScopeList {
	if in == nil {
		return nil
	}
	out := new(ClientScopeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClientScopeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientScopeSpec) DeepCopyInto(out *ClientScopeSpec) {
	*out = *in
	out.KeycloakRef = in.KeycloakRef
	if in.AdoptionPolicy != nil {
		in, out := &in.AdoptionPolicy, &out.AdoptionPolicy
		*out = new(AdoptionPolicy)
		**out = **in
	}
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(DeletionPolicy)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ProtocolMappers != nil {
		in, out := &in.ProtocolMappers, &out.ProtocolMappers
		*out = make([]ProtocolMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisplayOnConsentScreen != nil {
		in, out := &in.DisplayOnConsentScreen, &out.DisplayOnConsentScreen
		*out = new(bool)
		**out = **in
	}
	if in.ConsentScreenText != nil {
		in, out := &in.ConsentScreenText, &out.ConsentScreenText
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientScopeSpec.
func (in *ClientScopeSpec) DeepCopy() *ClientScopeSpec {
	if in == nil {
		return nil
	}
	out := new(ClientScopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec) DeepCopyInto(out *ClientSpec) {
	*out = *in
	out.KeycloakRef = in.KeycloakRef
	if in.AdoptionPolicy != nil {
		in, out := &in.AdoptionPolicy, &out.AdoptionPolicy
		*out = new(AdoptionPolicy)
		**out = **in
	}
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(DeletionPolicy)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.SecretOutput != nil {
		in, out := &in.SecretOutput, &out.SecretOutput
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.PublicClient != nil {
		in, out := &in.PublicClient, &out.PublicClient
		*out = new(bool)
		**out = **in
	}
	if in.BearerOnly != nil {
		in, out := &in.BearerOnly, &out.BearerOnly
		*out = new(bool)
		**out = **in
	}
	if in.StandardFlowEnabled != nil {
		in, out := &in.StandardFlowEnabled, &out.StandardFlowEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ImplicitFlowEnabled != nil {
		in, out := &in.ImplicitFlowEnabled, &out.ImplicitFlowEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DirectAccessGrantsEnabled != nil {
		in, out := &in.DirectAccessGrantsEnabled, &out.DirectAccessGrantsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ServiceAccountsEnabled != nil {
		in, out := &in.ServiceAccountsEnabled, &out.ServiceAccountsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AuthorizationServicesEnabled != nil {
		in, out := &in.AuthorizationServicesEnabled, &out.AuthorizationServicesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.FrontchannelLogout != nil {
		in, out := &in.FrontchannelLogout, &out.FrontchannelLogout
		*out = new(bool)
		**out = **in
	}
	if in.FullScopeAllowed != nil {
		in, out := &in.FullScopeAllowed, &out.FullScopeAllowed
		*out = new(bool)
		**out = **in
	}
	if in.ConsentRequired != nil {
		in, out := &in.ConsentRequired, &out.ConsentRequired
		*out = new(bool)
		**out = **in
	}
	if in.DisplayOnConsentScreen != nil {
		in, out := &in.DisplayOnConsentScreen, &out.DisplayOnConsentScreen
		*out = new(bool)
		**out = **in
	}
	if in.ConsentScreenText != nil {
		in, out := &in.ConsentScreenText, &out.ConsentScreenText
		*out = new(string)
		**out = **in
	}
	if in.AlwaysDisplayInConsole != nil {
		in, out := &in.AlwaysDisplayInConsole, &out.AlwaysDisplayInConsole
		*out = new(bool)
		**out = **in
	}
	if in.SurrogateAuthRequired != nil {
		in, out := &in.SurrogateAuthRequired, &out.SurrogateAuthRequired
		*out = new(bool)
		**out = **in
	}
	if in.RootURL != nil {
		in, out := &in.RootURL, &out.RootURL
		*out = new(string)
		**out = **in
	}
	if in.BaseURL != nil {
		in, out := &in.BaseURL, &out.BaseURL
		*out = new(string)
		**out = **in
	}
	if in.AdminURL != nil {
		in, out := &in.AdminURL, &out.AdminURL
		*out = new(string)
		**out = **in
	}
	if in.RedirectUris != nil {
		in, out := &in.RedirectUris, &out.RedirectUris
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebOrigins != nil {
		in, out := &in.WebOrigins, &out.WebOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeReRegistrationTimeout != nil {
		in, out := &in.NodeReRegistrationTimeout, &out.NodeReRegistrationTimeout
		*out = new(int)
		**out = **in
	}
	if in.ClientAuthenticatorType != nil {
		in, out := &in.ClientAuthenticatorType, &out.ClientAuthenticatorType
		*out = new(string)
		**out = **in
	}
	if in.ProtocolMappers != nil {
		in, out := &in.ProtocolMappers, &out.ProtocolMappers
		*out = make([]ProtocolMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultClientScopes != nil {
		in, out := &in.DefaultClientScopes, &out.DefaultClientScopes
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.OptionalClientScopes != nil {
		in, out := &in.OptionalClientScopes, &out.OptionalClientScopes
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AuthenticationFlowBindingOverrides != nil {
		in, out := &in.AuthenticationFlowBindingOverrides, &out.AuthenticationFlowBindingOverrides
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec.
func (in *ClientSpec) DeepCopy() *ClientSpec {
	if in == nil {
		return nil
	}
	out := new(ClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientStatus) DeepCopyInto(out *ClientStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientStatus.
func (in *ClientStatus) DeepCopy() *ClientStatus {
	if in == nil {
		return nil
	}
	out := new(ClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Group) DeepCopyInto(out *Group) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Group.
func (in *Group) DeepCopy() *Group {
	if in == nil {
		return nil
	}
	out := new(Group)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Group) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupList) DeepCopyInto(out *GroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Group, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupList.
func (in *GroupList) DeepCopy() *GroupList {
	if in == nil {
		return nil
	}
	out := new(GroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSpec) DeepCopyInto(out *GroupSpec) {
	*out = *in
	out.KeycloakRef = in.KeycloakRef
	if in.AdoptionPolicy != nil {
		in, out := &in.AdoptionPolicy, &out.AdoptionPolicy
		*out = new(AdoptionPolicy)
		**out = **in
	}
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(DeletionPolicy)
		**out = **in
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.RealmRoles != nil {
		in, out := &in.RealmRoles, &out.RealmRoles
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.ClientRoles != nil {
		in, out := &in.ClientRoles, &out.ClientRoles
		*out = new(map[string][]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string][]string, len(*in))
			for key, val := range *in {
				var outVal []string
				if val == nil {
					(*out)[key] = nil
				} else {
					inVal := (*in)[key]
					in, out := &inVal, &outVal
					*out = make([]string, len(*in))
					copy(*out, *in)
				}
				(*out)[key] = outVal
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSpec.
func (in *GroupSpec) DeepCopy() *GroupSpec {
	if in == nil {
		return nil
	}
	out := new(GroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProvider) DeepCopyInto(out *IdentityProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProvider.
func (in *IdentityProvider) DeepCopy() *IdentityProvider {
	if in == nil {
		return nil
	}
	out := new(IdentityProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentityProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderList) DeepCopyInto(out *IdentityProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IdentityProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderList.
func (in *IdentityProviderList) DeepCopy() *IdentityProviderList {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentityProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderMapper) DeepCopyInto(out *IdentityProviderMapper) {
	*out = *in
	if in.IdentityProviderMapper != nil {
		in, out := &in.IdentityProviderMapper, &out.IdentityProviderMapper
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderMapper.
func (in *IdentityProviderMapper) DeepCopy() *IdentityProviderMapper {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderSpec) DeepCopyInto(out *IdentityProviderSpec) {
	*out = *in
	out.KeycloakRef = in.KeycloakRef
	if in.AdoptionPolicy != nil {
		in, out := &in.AdoptionPolicy, &out.AdoptionPolicy
		*out = new(AdoptionPolicy)
		**out = **in
	}
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(DeletionPolicy)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.TrustEmail != nil {
		in, out := &in.TrustEmail, &out.TrustEmail
		*out = new(bool)
		**out = **in
	}
	if in.StoreToken != nil {
		in, out := &in.StoreToken, &out.StoreToken
		*out = new(bool)
		**out = **in
	}
	if in.AddReadTokenRoleOnCreate != nil {
		in, out := &in.AddReadTokenRoleOnCreate, &out.AddReadTokenRoleOnCreate
		*out = new(bool)
		**out = **in
	}
	if in.LinkOnly != nil {
		in, out := &in.LinkOnly, &out.LinkOnly
		*out = new(bool)
		**out = **in
	}
	if in.FirstBrokerLoginFlowAlias != nil {
		in, out := &in.FirstBrokerLoginFlowAlias, &out.FirstBrokerLoginFlowAlias
		*out = new(string)
		**out = **in
	}
	if in.PostBrokerLoginFlowAlias != nil {
		in, out := &in.PostBrokerLoginFlowAlias, &out.PostBrokerLoginFlowAlias
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigSecretRef != nil {
		in, out := &in.ConfigSecretRef, &out.ConfigSecretRef
		*out = new(SecretKeysSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Mappers != nil {
		in, out := &in.Mappers, &out.Mappers
		*out = make([]IdentityProviderMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderSpec.
func (in *IdentityProviderSpec) DeepCopy() *IdentityProviderSpec {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakConnection) DeepCopyInto(out *KeycloakConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakConnection.
func (in *KeycloakConnection) DeepCopy() *KeycloakConnection {
	if in == nil {
		return nil
	}
	out := new(KeycloakConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakConnectionList) DeepCopyInto(out *KeycloakConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakConnectionList.
func (in *KeycloakConnectionList) DeepCopy() *KeycloakConnectionList {
	if in == nil {
		return nil
	}
	out := new(KeycloakConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakConnectionSpec) DeepCopyInto(out *KeycloakConnectionSpec) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthType)
		**out = **in
	}
	if in.AdminRealm != nil {
		in, out := &in.AdminRealm, &out.AdminRealm
		*out = new(string)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakConnectionSpec.
func (in *KeycloakConnectionSpec) DeepCopy() *KeycloakConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakConnectionStatus) DeepCopyInto(out *KeycloakConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakConnectionStatus.
func (in *KeycloakConnectionStatus) DeepCopy() *KeycloakConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRef) DeepCopyInto(out *KeycloakRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRef.
func (in *KeycloakRef) DeepCopy() *KeycloakRef {
	if in == nil {
		return nil
	}
	out := new(KeycloakRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolMapper) DeepCopyInto(out *ProtocolMapper) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.ProtocolMapper != nil {
		in, out := &in.ProtocolMapper, &out.ProtocolMapper
		*out = new(string)
		**out = **in
	}
	if in.ConsentRequired != nil {
		in, out := &in.ConsentRequired, &out.ConsentRequired
		*out = new(bool)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolMapper.
func (in *ProtocolMapper) DeepCopy() *ProtocolMapper {
	if in == nil {
		return nil
	}
	out := new(ProtocolMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Realm) DeepCopyInto(out *Realm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Realm.
func (in *Realm) DeepCopy() *Realm {
	if in == nil {
		return nil
	}
	out := new(Realm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Realm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmList) DeepCopyInto(out *RealmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Realm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmList.
func (in *RealmList) DeepCopy() *RealmList {
	if in == nil {
		return nil
	}
	out := new(RealmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RealmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmRole) DeepCopyInto(out *RealmRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmRole.
func (in *RealmRole) DeepCopy() *RealmRole {
	if in == nil {
		return nil
	}
	out := new(RealmRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RealmRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmRoleList) DeepCopyInto(out *RealmRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RealmRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmRoleList.
func (in *RealmRoleList) DeepCopy() *RealmRoleList {
	if in == nil {
		return nil
	}
	out := new(RealmRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RealmRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmRoleSpec) DeepCopyInto(out *RealmRoleSpec) {
	*out = *in
	out.KeycloakRef = in.KeycloakRef
	if in.AdoptionPolicy != nil {
		in, out := &in.AdoptionPolicy, &out.AdoptionPolicy
		*out = new(AdoptionPolicy)
		**out = **in
	}
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(DeletionPolicy)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Composite != nil {
		in, out := &in.Composite, &out.Composite
		*out = new(bool)
		**out = **in
	}
	if in.Composites != nil {
		in, out := &in.Composites, &out.Composites
		*out = new(RoleComposites)
		(*in).DeepCopyInto(*out)
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmRoleSpec.
func (in *RealmRoleSpec) DeepCopy() *RealmRoleSpec {
	if in == nil {
		return nil
	}
	out := new(RealmRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmSpec) DeepCopyInto(out *RealmSpec) {
	*out = *in
	out.KeycloakRef = in.KeycloakRef
	if in.AdoptionPolicy != nil {
		in, out := &in.AdoptionPolicy, &out.AdoptionPolicy
		*out = new(AdoptionPolicy)
		**out = **in
	}
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(DeletionPolicy)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DisplayNameHTML != nil {
		in, out := &in.DisplayNameHTML, &out.DisplayNameHTML
		*out = new(string)
		**out = **in
	}
	if in.SSLRequired != nil {
		in, out := &in.SSLRequired, &out.SSLRequired
		*out = new(string)
		**out = **in
	}
	if in.NotBefore != nil {
		in, out := &in.NotBefore, &out.NotBefore
		*out = new(int)
		**out = **in
	}
	if in.RegistrationAllowed != nil {
		in, out := &in.RegistrationAllowed, &out.RegistrationAllowed
		*out = new(bool)
		**out = **in
	}
	if in.RegistrationEmailAsUsername != nil {
		in, out := &in.RegistrationEmailAsUsername, &out.RegistrationEmailAsUsername
		*out = new(bool)
		**out = **in
	}
	if in.LoginWithEmailAllowed != nil {
		in, out := &in.LoginWithEmailAllowed, &out.LoginWithEmailAllowed
		*out = new(bool)
		**out = **in
	}
	if in.DuplicateEmailsAllowed != nil {
		in, out := &in.DuplicateEmailsAllowed, &out.DuplicateEmailsAllowed
		*out = new(bool)
		**out = **in
	}
	if in.ResetPasswordAllowed != nil {
		in, out := &in.ResetPasswordAllowed, &out.ResetPasswordAllowed
		*out = new(bool)
		**out = **in
	}
	if in.RememberMe != nil {
		in, out := &in.RememberMe, &out.RememberMe
		*out = new(bool)
		**out = **in
	}
	if in.VerifyEmail != nil {
		in, out := &in.VerifyEmail, &out.VerifyEmail
		*out = new(bool)
		**out = **in
	}
	if in.UserManagedAccessAllowed != nil {
		in, out := &in.UserManagedAccessAllowed, &out.UserManagedAccessAllowed
		*out = new(bool)
		**out = **in
	}
	if in.SSOSessionIdleTimeout != nil {
		in, out := &in.SSOSessionIdleTimeout, &out.SSOSessionIdleTimeout
		*out = new(int)
		**out = **in
	}
	if in.SSOSessionMaxLifespan != nil {
		in, out := &in.SSOSessionMaxLifespan, &out.SSOSessionMaxLifespan
		*out = new(int)
		**out = **in
	}
	if in.SSOSessionIdleTimeoutRememberMe != nil {
		in, out := &in.SSOSessionIdleTimeoutRememberMe, &out.SSOSessionIdleTimeoutRememberMe
		*out = new(int)
		**out = **in
	}
	if in.SSOSessionMaxLifespanRememberMe != nil {
		in, out := &in.SSOSessionMaxLifespanRememberMe, &out.SSOSessionMaxLifespanRememberMe
		*out = new(int)
		**out = **in
	}
	if in.ClientSessionIdleTimeout != nil {
		in, out := &in.ClientSessionIdleTimeout, &out.ClientSessionIdleTimeout
		*out = new(int)
		**out = **in
	}
	if in.ClientSessionMaxLifespan != nil {
		in, out := &in.ClientSessionMaxLifespan, &out.ClientSessionMaxLifespan
		*out = new(int)
		**out = **in
	}
	if in.ClientOfflineSessionIdleTimeout != nil {
		in, out := &in.ClientOfflineSessionIdleTimeout, &out.ClientOfflineSessionIdleTimeout
		*out = new(int)
		**out = **in
	}
	if in.ClientOfflineSessionMaxLifespan != nil {
		in, out := &in.ClientOfflineSessionMaxLifespan, &out.ClientOfflineSessionMaxLifespan
		*out = new(int)
		**out = **in
	}
	if in.AccessTokenLifespan != nil {
		in, out := &in.AccessTokenLifespan, &out.AccessTokenLifespan
		*out = new(int)
		**out = **in
	}
	if in.AccessTokenLifespanForImplicitFlow != nil {
		in, out := &in.AccessTokenLifespanForImplicitFlow, &out.AccessTokenLifespanForImplicitFlow
		*out = new(int)
		**out = **in
	}
	if in.OfflineSessionIdleTimeout != nil {
		in, out := &in.OfflineSessionIdleTimeout, &out.OfflineSessionIdleTimeout
		*out = new(int)
		**out = **in
	}
	if in.OfflineSessionMaxLifespanEnabled != nil {
		in, out := &in.OfflineSessionMaxLifespanEnabled, &out.OfflineSessionMaxLifespanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.OfflineSessionMaxLifespan != nil {
		in, out := &in.OfflineSessionMaxLifespan, &out.OfflineSessionMaxLifespan
		*out = new(int)
		**out = **in
	}
	if in.AccessCodeLifespan != nil {
		in, out := &in.AccessCodeLifespan, &out.AccessCodeLifespan
		*out = new(int)
		**out = **in
	}
	if in.AccessCodeLifespanUserAction != nil {
		in, out := &in.AccessCodeLifespanUserAction, &out.AccessCodeLifespanUserAction
		*out = new(int)
		**out = **in
	}
	if in.AccessCodeLifespanLogin != nil {
		in, out := &in.AccessCodeLifespanLogin, &out.AccessCodeLifespanLogin
		*out = new(int)
		**out = **in
	}
	if in.ActionTokenGeneratedByAdminLifespan != nil {
		in, out := &in.ActionTokenGeneratedByAdminLifespan, &out.ActionTokenGeneratedByAdminLifespan
		*out = new(int)
		**out = **in
	}
	if in.ActionTokenGeneratedByUserLifespan != nil {
		in, out := &in.ActionTokenGeneratedByUserLifespan, &out.ActionTokenGeneratedByUserLifespan
		*out = new(int)
		**out = **in
	}
	if in.OAuth2DeviceCodeLifespan != nil {
		in, out := &in.OAuth2DeviceCodeLifespan, &out.OAuth2DeviceCodeLifespan
		*out = new(int)
		**out = **in
	}
	if in.OAuth2DevicePollingInterval != nil {
		in, out := &in.OAuth2DevicePollingInterval, &out.OAuth2DevicePollingInterval
		*out = new(int)
		**out = **in
	}
	if in.RevokeRefreshToken != nil {
		in, out := &in.RevokeRefreshToken, &out.RevokeRefreshToken
		*out = new(bool)
		**out = **in
	}
	if in.RefreshTokenMaxReuse != nil {
		in, out := &in.RefreshTokenMaxReuse, &out.RefreshTokenMaxReuse
		*out = new(int)
		**out = **in
	}
	if in.LoginTheme != nil {
		in, out := &in.LoginTheme, &out.LoginTheme
		*out = new(string)
		**out = **in
	}
	if in.AccountTheme != nil {
		in, out := &in.AccountTheme, &out.AccountTheme
		*out = new(string)
		**out = **in
	}
	if in.AdminTheme != nil {
		in, out := &in.AdminTheme, &out.AdminTheme
		*out = new(string)
		**out = **in
	}
	if in.EmailTheme != nil {
		in, out := &in.EmailTheme, &out.EmailTheme
		*out = new(string)
		**out = **in
	}
	if in.SMTPServer != nil {
		in, out := &in.SMTPServer, &out.SMTPServer
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SMTPServerSecretRef != nil {
		in, out := &in.SMTPServerSecretRef, &out.SMTPServerSecretRef
		*out = new(SecretKeysSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.EventsEnabled != nil {
		in, out := &in.EventsEnabled, &out.EventsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EventsExpiration != nil {
		in, out := &in.EventsExpiration, &out.EventsExpiration
		*out = new(int64)
		**out = **in
	}
	if in.EventsListeners != nil {
		in, out := &in.EventsListeners, &out.EventsListeners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnabledEventTypes != nil {
		in, out := &in.EnabledEventTypes, &out.EnabledEventTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdminEventsEnabled != nil {
		in, out := &in.AdminEventsEnabled, &out.AdminEventsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AdminEventsDetailsEnabled != nil {
		in, out := &in.AdminEventsDetailsEnabled, &out.AdminEventsDetailsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PasswordPolicy != nil {
		in, out := &in.PasswordPolicy, &out.PasswordPolicy
		*out = new(string)
		**out = **in
	}
	if in.BruteForceProtected != nil {
		in, out := &in.BruteForceProtected, &out.BruteForceProtected
		*out = new(bool)
		**out = **in
	}
	if in.PermanentLockout != nil {
		in, out := &in.PermanentLockout, &out.PermanentLockout
		*out = new(bool)
		**out = **in
	}
	if in.MaxFailureWaitSeconds != nil {
		in, out := &in.MaxFailureWaitSeconds, &out.MaxFailureWaitSeconds
		*out = new(int)
		**out = **in
	}
	if in.MinimumQuickLoginWaitSeconds != nil {
		in, out := &in.MinimumQuickLoginWaitSeconds, &out.MinimumQuickLoginWaitSeconds
		*out = new(int)
		**out = **in
	}
	if in.WaitIncrementSeconds != nil {
		in, out := &in.WaitIncrementSeconds, &out.WaitIncrementSeconds
		*out = new(int)
		**out = **in
	}
	if in.QuickLoginCheckMilliSeconds != nil {
		in, out := &in.QuickLoginCheckMilliSeconds, &out.QuickLoginCheckMilliSeconds
		*out = new(int64)
		**out = **in
	}
	if in.MaxDeltaTimeSeconds != nil {
		in, out := &in.MaxDeltaTimeSeconds, &out.MaxDeltaTimeSeconds
		*out = new(int)
		**out = **in
	}
	if in.FailureFactor != nil {
		in, out := &in.FailureFactor, &out.FailureFactor
		*out = new(int)
		**out = **in
	}
	if in.OTPPolicyType != nil {
		in, out := &in.OTPPolicyType, &out.OTPPolicyType
		*out = new(string)
		**out = **in
	}
	if in.OTPPolicyAlgorithm != nil {
		in, out := &in.OTPPolicyAlgorithm, &out.OTPPolicyAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.OTPPolicyInitialCounter != nil {
		in, out := &in.OTPPolicyInitialCounter, &out.OTPPolicyInitialCounter
		*out = new(int)
		**out = **in
	}
	if in.OTPPolicyDigits != nil {
		in, out := &in.OTPPolicyDigits, &out.OTPPolicyDigits
		*out = new(int)
		**out = **in
	}
	if in.OTPPolicyLookAheadWindow != nil {
		in, out := &in.OTPPolicyLookAheadWindow, &out.OTPPolicyLookAheadWindow
		*out = new(int)
		**out = **in
	}
	if in.OTPPolicyPeriod != nil {
		in, out := &in.OTPPolicyPeriod, &out.OTPPolicyPeriod
		*out = new(int)
		**out = **in
	}
	if in.OTPPolicyCodeReusable != nil {
		in, out := &in.OTPPolicyCodeReusable, &out.OTPPolicyCodeReusable
		*out = new(bool)
		**out = **in
	}
	if in.WebAuthnPolicyRpEntityName != nil {
		in, out := &in.WebAuthnPolicyRpEntityName, &out.WebAuthnPolicyRpEntityName
		*out = new(string)
		**out = **in
	}
	if in.WebAuthnPolicySignatureAlgorithms != nil {
		in, out := &in.WebAuthnPolicySignatureAlgorithms, &out.WebAuthnPolicySignatureAlgorithms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebAuthnPolicyRpID != nil {
		in, out := &in.WebAuthnPolicyRpID, &out.WebAuthnPolicyRpID
		*out = new(string)
		**out = **in
	}
	if in.WebAuthnPolicyAttestationConveyancePreference != nil {
		in, out := &in.WebAuthnPolicyAttestationConveyancePreference, &out.WebAuthnPolicyAttestationConveyancePreference
		*out = new(string)
		**out = **in
	}
	if in.WebAuthnPolicyAuthenticatorAttachment != nil {
		in, out := &in.WebAuthnPolicyAuthenticatorAttachment, &out.WebAuthnPolicyAuthenticatorAttachment
		*out = new(string)
		**out = **in
	}
	if in.WebAuthnPolicyRequireResidentKey != nil {
		in, out := &in.WebAuthnPolicyRequireResidentKey, &out.WebAuthnPolicyRequireResidentKey
		*out = new(string)
		**out = **in
	}
	if in.WebAuthnPolicyUserVerificationRequirement != nil {
		in, out := &in.WebAuthnPolicyUserVerificationRequirement, &out.WebAuthnPolicyUserVerificationRequirement
		*out = new(string)
		**out = **in
	}
	if in.WebAuthnPolicyCreateTimeout != nil {
		in, out := &in.WebAuthnPolicyCreateTimeout, &out.WebAuthnPolicyCreateTimeout
		*out = new(int)
		**out = **in
	}
	if in.WebAuthnPolicyAvoidSameAuthenticatorRegister != nil {
		in, out := &in.WebAuthnPolicyAvoidSameAuthenticatorRegister, &out.WebAuthnPolicyAvoidSameAuthenticatorRegister
		*out = new(bool)
		**out = **in
	}
	if in.WebAuthnPolicyAcceptableAaguids != nil {
		in, out := &in.WebAuthnPolicyAcceptableAaguids, &out.WebAuthnPolicyAcceptableAaguids
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebAuthnPolicyPasswordlessRpEntityName != nil {
		in, out := &in.WebAuthnPolicyPasswordlessRpEntityName, &out.WebAuthnPolicyPasswordlessRpEntityName
		*out = new(string)
		**out = **in
	}
	if in.WebAuthnPolicyPasswordlessSignatureAlgorithms != nil {
		in, out := &in.WebAuthnPolicyPasswordlessSignatureAlgorithms, &out.WebAuthnPolicyPasswordlessSignatureAlgorithms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebAuthnPolicyPasswordlessRpID != nil {
		in, out := &in.WebAuthnPolicyPasswordlessRpID, &out.WebAuthnPolicyPasswordlessRpID
		*out = new(string)
		**out = **in
	}
	if in.WebAuthnPolicyPasswordlessAttestationConveyancePreference != nil {
		in, out := &in.WebAuthnPolicyPasswordlessAttestationConveyancePreference, &out.WebAuthnPolicyPasswordlessAttestationConveyancePreference
		*out = new(string)
		**out = **in
	}
	if in.WebAuthnPolicyPasswordlessAuthenticatorAttachment != nil {
		in, out := &in.WebAuthnPolicyPasswordlessAuthenticatorAttachment, &out.WebAuthnPolicyPasswordlessAuthenticatorAttachment
		*out = new(string)
		**out = **in
	}
	if in.WebAuthnPolicyPasswordlessRequireResidentKey != nil {
		in, out := &in.WebAuthnPolicyPasswordlessRequireResidentKey, &out.WebAuthnPolicyPasswordlessRequireResidentKey
		*out = new(string)
		**out = **in
	}
	if in.WebAuthnPolicyPasswordlessUserVerificationRequirement != nil {
		in, out := &in.WebAuthnPolicyPasswordlessUserVerificationRequirement, &out.WebAuthnPolicyPasswordlessUserVerificationRequirement
		*out = new(string)
		**out = **in
	}
	if in.WebAuthnPolicyPasswordlessCreateTimeout != nil {
		in, out := &in.WebAuthnPolicyPasswordlessCreateTimeout, &out.WebAuthnPolicyPasswordlessCreateTimeout
		*out = new(int)
		**out = **in
	}
	if in.WebAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister != nil {
		in, out := &in.WebAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister, &out.WebAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister
		*out = new(bool)
		**out = **in
	}
	if in.WebAuthnPolicyPasswordlessAcceptableAaguids != nil {
		in, out := &in.WebAuthnPolicyPasswordlessAcceptableAaguids, &out.WebAuthnPolicyPasswordlessAcceptableAaguids
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InternationalizationEnabled != nil {
		in, out := &in.InternationalizationEnabled, &out.InternationalizationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SupportedLocales != nil {
		in, out := &in.SupportedLocales, &out.SupportedLocales
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultLocale != nil {
		in, out := &in.DefaultLocale, &out.DefaultLocale
		*out = new(string)
		**out = **in
	}
	if in.DefaultDefaultClientScopes != nil {
		in, out := &in.DefaultDefaultClientScopes, &out.DefaultDefaultClientScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultOptionalClientScopes != nil {
		in, out := &in.DefaultOptionalClientScopes, &out.DefaultOptionalClientScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultSignatureAlgorithm != nil {
		in, out := &in.DefaultSignatureAlgorithm, &out.DefaultSignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.BrowserSecurityHeaders != nil {
		in, out := &in.BrowserSecurityHeaders, &out.BrowserSecurityHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.OrganizationsEnabled != nil {
		in, out := &in.OrganizationsEnabled, &out.OrganizationsEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmSpec.
func (in *RealmSpec) DeepCopy() *RealmSpec {
	if in == nil {
		return nil
	}
	out := new(RealmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatus.
func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleComposites) DeepCopyInto(out *RoleComposites) {
	*out = *in
	if in.RealmRoles != nil {
		in, out := &in.RealmRoles, &out.RealmRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClientRoles != nil {
		in, out := &in.ClientRoles, &out.ClientRoles
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleComposites.
func (in *RoleComposites) DeepCopy() *RoleComposites {
	if in == nil {
		return nil
	}
	out := new(RoleComposites)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeysSelector) DeepCopyInto(out *SecretKeysSelector) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeysSelector.
func (in *SecretKeysSelector) DeepCopy() *SecretKeysSelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeysSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}
